### ISSUE TITLE
Add Screenshots to Readme

### ISSUE THREAD

**Issue by TheCodeTraveler** [brminnick/SimpleXamarinGraphQL#1]
![ScreenFlow](https://user-images.githubusercontent.com/13558917/61123995-69809080-a46b-11e9-92c4-c5c0174f4e1a.gif)

**Comment by brminnick** [comment]
<img width="1680" alt="Screen Shot 2019-07-15 at 5 02 46 PM" src="https://user-images.githubusercontent.com/13558917/61256668-6a8f1780-a722-11e9-97ad-8188ec6eab8f.png">
